# サウンドフォントの格納ディレクトリ (末尾スラッシュ推奨)
soundfont.directory=/usr/share/soundfonts/

# サウンドフォントのエイリアス設定 (soundfont.aliases.<エイリアス名>=<ファイル名>)
soundfont.aliases.GeneralUser=GeneralUser.sf2
soundfont.aliases.FluidR3_GM=FluidR3_GM.sf2
